### ISSUE TITLE
Failed to resolve entry for package

### ISSUE THREAD

**Issue by LeonSolisPedro** [kingyue737/vite-plugin-browserslist-useragent#1]
Hi. I'm trying to use this plugin in Vite with vue.

I follow the instructions and this error appears:

`ERROR: [plugin: externalize-deps] Failed to resolve entry for package "vite-plugin-browserslist-useragent". The package may have incorrect main/module/exports specified in its package.json: No known conditions for "." entry in "vite-plugin-browserslist-useragent" package`

Can someone explain me what am I doing wrong?

**Comment by kingyue737** [comment]
Hi @LeonSolisPedro , as mentioned in README, the dependency `browserslist-useragent-regex` has dropped support for CJS https://github.com/browserslist/browserslist-useragent-regexp/commit/41456bc22b789fee57384a00abb64e0690ded08a. The latest version of this plugin only support ESM. You need to rename `vite.config.js` to `vite.config.mjs`  in order to import this plugin. Or downgrade to v0.1.0. I will try to support CJS later.

**Comment by LeonSolisPedro** [comment]
Thanks.
