### ISSUE TITLE
How do we auto-keep the browserslist DB up to date?

### ISSUE THREAD

**Issue by litera** [kingyue737/vite-plugin-browserslist-useragent#12]
This plugin is a nice plugin, but what does it actually solve? Ok, so we don't need to manually run the CLI to regenerate the module with the regular expression every time we change the browserslist configuration. Fine. But IMO that list doesn't really change too often when it's set. **What does change often without developers' intervention are browser versions.**

That's why despite using this plugin we still need to manually upgrade browserslist/DB... What if the browserslist version increments beyond the dependency version definition of this vite plugin? How do we know this plugin will be regularly updated? **How do we assure we regularly update this plugin?**

That's why I'm asking whether this plugin actually solves anything significant?

The perfect solution IMO would be that whenever we make a vite build, the DB would get upgraded to latest and then this vite plugin would be able to generate latest regex.

**Comment by kingyue737** [comment]
Thanks for your suggestion!

> That's why I'm asking whether this plugin actually solves anything significant?

I want the browserslist config to be the single source of truth. In my end projects, I don't want to include the module with the regular expression, an output instead of source code. That's why I made the module with the regular expression an virtual module generated by vite plugin. Not something significant but preferred by some users https://github.com/kingyue737/vite-plugin-browserslist-useragent/issues/2#issuecomment-1876160836

> That's why despite using this plugin we still need to manually upgrade browserslist/DB...

I think browserslist/DB or other dependencies in your project should be managed by `renovate`/`dependabot`/`yourself` instead of a vite plugin. Most of the time you just need to run `pnpm update`.

> But IMO that list doesn't really change too often when it's set.

The list doesn't change too often but the regex does if your target browsers is something like `last three versions`. In this case, your project is actively maintained, and it's a good practice to update all the dependencies besides browserslist/DB.

> What if the browserslist version increments beyond the dependency version definition of this vite plugin? How do we know this plugin will be regularly updated? How do we assure we regularly update this plugin?

Browserslist v4 was published 6 years ago. This plugin does not need regular update. I will update this plugin when there are breaking changes to its dependency in the future. Or PR/fork welcome. Before I update the plugin, you can also override the version of browserslist via package manager:

```json
// package.json for yarn
{
  "dependencies": {

  },
  "resolutions": {
    "browserslist": "^5.0.0"
  }
}
```

```json
// package.json for npm
{
  "dependencies": {

  },
  "overrides": {
    "browserslist": "^5.0.0"
  }
}
```

> The perfect solution IMO would be that whenever we make a vite build, the DB would get upgraded to latest.

You can achieve this via `script` in `package.json` like:
```
{
  "scripts": {
    "build": " npm update caniuse-lite browserslist && vite build",
  },
}
```
